services:

  api:
    extends:
      file: docker-compose.yml
      service: n_api
    profiles:
      - "node"
    # For a production deployment, we want to avoid binding ports to the host to avoid conflicts with
    # already running services. So here we override the ports exposed in the recipe we expand from and
    # set the ports to an empty list
    ports: !override []
    environment:
      VIRTUAL_HOST: ${NB_NAPI_DOMAIN:-${NB_DEPLOY_DOMAIN}}
      VIRTUAL_PATH: ${NB_NAPI_BASE_PATH:-/}
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: ${NB_NAPI_DOMAIN:-${NB_DEPLOY_DOMAIN}}
  
  graph:
    extends:
      file: docker-compose.yml
      service: graph
    profiles:
      - "node"
    # For a production deployment, we want to avoid binding ports to the host to avoid conflicts with
    # already running services. So here we override the ports exposed in the recipe we expand from and
    # set the ports to an empty list
    ports: !override []

  f_api:
    extends:
      file: docker-compose.yml
      service: f_api
    profiles:
      - "portal"
    # For a production deployment, we want to avoid binding ports to the host to avoid conflicts with
    # already running services. So here we override the ports exposed in the recipe we expand from and
    # set the ports to an empty list
    ports: !override []
    environment:
      VIRTUAL_HOST: ${NB_FAPI_DOMAIN:-${NB_DEPLOY_DOMAIN}}
      VIRTUAL_PATH: ${NB_FAPI_BASE_PATH:-/}
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: ${NB_FAPI_DOMAIN:-${NB_DEPLOY_DOMAIN}}

  query:
    extends:
      file: docker-compose.yml
      service: query
    profiles:
      - "node"
    # For a production deployment, we want to avoid binding ports to the host to avoid conflicts with
    # already running services. So here we override the ports exposed in the recipe we expand from and
    # set the ports to an empty list
    ports: !override []
    environment:
      NB_API_QUERY_URL: https://${NB_FAPI_DOMAIN:-${NB_DEPLOY_DOMAIN}}${NB_FAPI_BASE_PATH}
      # Replace the below domain with the domain you want to serve the query tool from
      VIRTUAL_HOST: ${NB_QUERY_DOMAIN:-${NB_DEPLOY_DOMAIN}}
      VIRTUAL_PATH: ${NB_QUERY_APP_BASE_PATH:-/}
      VIRTUAL_PORT: 5173
      # Set the below to the same domain as VIRTUAL_HOST to enable HTTPS
      LETSENCRYPT_HOST: ${NB_QUERY_DOMAIN:-${NB_DEPLOY_DOMAIN}}

secrets:
  db_admin_password:
    file: ${NB_GRAPH_SECRETS_PATH:-./secrets}/NB_GRAPH_ADMIN_PASSWORD.txt
  db_user_password:
    file: ${NB_GRAPH_SECRETS_PATH:-./secrets}/NB_GRAPH_PASSWORD.txt

volumes:
  graphdb_home:

networks:
  proxy-net:
    external: true
    name: ${PROXY_NETWORK_NAME:-NB_proxynet}